from sys_ import *
import um
c=um.c
# Eltern: blue header band
c.add('.bh-el-head',SEC,{"background-color":BLUE,"color":PAPER,**box(["clamp(56px, 7vw, 96px)",PADX,"clamp(48px, 6vw, 80px)",PADX])})
c.add('.bh-el-h1',{"margin-top":"0px","margin-bottom":"16px","font-family":HF,"font-weight":"700","font-size":"clamp(2.8rem, 4vw + 1rem, 5rem)","line-height":"1.02","color":PAPER})
c.add('.bh-el-lead',{"margin-top":"0px","margin-bottom":"0px","max-width":"56ch","font-size":"1.25rem","color":"#E4EAF5"})
c.add('.bh-el-toc',{"display":"flex","flex-wrap":"wrap","column-gap":"8px","row-gap":"8px","margin-top":"32px"})
c.add('.bh-el-toc-link',{"display":"inline-flex","align-items":"center","min-height":"44px",**box(["0px","14px","0px","14px"]),"background-color":"#FFFFFF",**brd(f"1.5px solid {INK}"),**rad("4px"),"font-family":HF,"font-weight":"600","font-size":"0.9375rem","color":INK,"text-decoration":"none"})
c.add('.bh-el-toc-link:hover',{"background-color":MARK})
c.add('.bh-el-toc-link:focus',FOCUS)
c.add('.bh-note-box',{"margin-top":"28px","max-width":"62ch",**box(["16px","20px","16px","20px"]),"background-color":"#FFFFFF",**brd(f"1.5px solid {INK}"),**rad("4px")})
c.add('.bh-tips',{"margin-top":"0px","margin-bottom":"0px","padding-left":"22px","max-width":"66ch"})
c.add('.bh-tips-li',{"margin-bottom":"12px"})
# Kinder: green band + notebook
c.add('.bh-kid',SEC,{"background-color":GREEN,"color":INK,**box(["clamp(56px, 7vw, 96px)",PADX,"clamp(72px, 9vw, 128px)",PADX])})
c.add('.bh-kid-h1',{"margin-top":"0px","margin-bottom":"16px","font-family":HF,"font-weight":"700","font-size":"clamp(2.8rem, 4vw + 1rem, 5rem)","line-height":"1.02","color":INK})
c.add('.bh-kid-lead',{"margin-top":"0px","margin-bottom":"0px","max-width":"50ch","font-size":"1.3125rem","color":INK})
c.add('.bh-kblock',{"margin-top":"56px","max-width":"860px","background-color":"#FFFFFF","color":INK,**rad("4px"),"background-image":"repeating-linear-gradient(transparent 0px, transparent 35px, #D9E1EC 35px, #D9E1EC 36px)","background-position":"0 36px","border-top":f"10px dotted {GREEN}",**box(["40px","clamp(20px, 5vw, 64px)","48px","clamp(20px, 5vw, 64px)"]),"line-height":"36px","font-size":"1.3125rem"})
c.add('.bh-kblock-h',{"margin-top":"36px","margin-bottom":"0px","font-family":HF,"font-weight":"700","font-size":"1.625rem","line-height":"36px","color":INK})
c.add('.bh-kblock-p',{"margin-top":"0px","margin-bottom":"0px","max-width":"52ch"})
c.add('.bh-kid-room',PH,{"margin-top":"36px","min-height":"220px","border-top-style":"dashed","border-right-style":"dashed","border-bottom-style":"dashed","border-left-style":"dashed"})
c.add('.bh-kid-parents',{"margin-top":"40px","margin-bottom":"0px","max-width":"60ch","font-size":"1.0625rem"})
c.add('.bh-tlink-ink',TLINK,{"text-decoration-color":INK}); c.add('.bh-tlink-ink:hover',{"color":PAPER}); c.add('.bh-tlink-ink:focus',FOCUS)

c.add('.bh-after',{'margin-top':'24px','margin-bottom':'0px'})
EL=[]
EL.append(('head','<section class="bh-el-head" aria-labelledby="h-el"><h1 id="h-el" class="bh-el-h1">Für Eltern</h1><p class="bh-el-lead">Sie machen sich Sorgen um Ihr Kind und überlegen, ob eine Therapie helfen könnte. Auf dieser Seite steht, was Sie vor dem ersten Anruf wissen sollten.</p><nav class="bh-el-toc" aria-label="Auf dieser Seite"><a href="#wann" class="bh-el-toc-link">Wann Hilfe sinnvoll ist</a><a href="#rolle" class="bh-el-toc-link">Ihre Rolle</a><a href="#vorbereiten" class="bh-el-toc-link">Ihr Kind vorbereiten</a><a href="#kosten" class="bh-el-toc-link">Kosten</a></nav></section>'))
signs=["Ein Problem hält seit Wochen an und wird nicht von allein besser.","Ihr Kind meidet Dinge, die ihm früher leichtfielen, etwa Schule, Freunde oder Hobbys.","Schlaf, Essen oder Stimmung haben sich deutlich verändert.","Es gibt zu Hause fast täglich Streit, und alle sind erschöpft.","Nach einer Trennung, einem Umzug oder einem Todesfall kommt Ihr Kind nicht zur Ruhe.","Sie wissen selbst nicht mehr, wie Sie Ihrem Kind helfen können."]
EL.append(('wann','<section id="wann" class="bh-anl" aria-labelledby="h-wann"><h2 id="h-wann" class="bh-h2">Wann eine Therapie sinnvoll sein kann</h2><p class="bh-um-lead">Jedes Kind hat schwierige Phasen. Ein Anruf lohnt sich, wenn Sie etwas davon über längere Zeit beobachten:</p><ul class="bh-anl-list">'+''.join(f'<li class="bh-anl-li">{s}</li>' for s in signs)+'</ul><p class="bh-note-box">Sie müssen vorher nicht sicher sein, dass Ihr Kind eine Therapie braucht. Das klären wir gemeinsam im Erstgespräch. Wenn eine Beratungsstelle oder eine andere Hilfe besser passt, sage ich Ihnen das.</p></section>'))
role=[("Regelmäßige Elterngespräche",'<span class="bh-mark">Alle vier Sitzungen</span> sprechen wir ohne Ihr Kind miteinander. Es geht darum, was Sie zu Hause beobachten und was im Alltag helfen kann.'),("Vertrauen Ihres Kindes schützen","Einzelheiten aus den Stunden erzähle ich nur weiter, wenn Ihr Kind einverstanden ist. Wie es insgesamt läuft, erfahren Sie immer. Bei einer ernsten Gefahr handle ich sofort."),("Zustimmung beider Sorgeberechtigten","Bei gemeinsamem Sorgerecht braucht es in der Regel beide Unterschriften, auch wenn Sie getrennt leben. Wenn das schwierig ist, sprechen Sie mich an.")]
EL.append(('rolle','<section id="rolle" class="bh-um-sec" aria-labelledby="h-rolle"><h2 id="h-rolle" class="bh-h2">Ihre Rolle in der Therapie</h2><p class="bh-um-lead">Ihr Kind hat seine Stunden allein mit mir. Sie bleiben trotzdem ein wichtiger Teil der Therapie, denn Veränderungen passieren vor allem zu Hause.</p><div class="bh-hold">'+''.join(f'<div class="bh-hold-item"><h3 class="bh-h3">{h}</h3><p class="bh-p">{t}</p></div>' for h,t in role)+'</div></section>'))
tips=["Sagen Sie Ihrem Kind ehrlich und in einfachen Worten, wohin Sie gehen. Zum Beispiel: Wir besuchen Frau Behr. Sie hilft Kindern, wenn etwas schwer ist.","Erklären Sie, warum. Ohne Vorwurf und mit Blick auf das, was Ihr Kind selbst belastet.","Versprechen Sie nichts, was nicht stimmt. Die Stunden sind oft spielerisch, aber es wird auch über Schwieriges gesprochen.","Lesen Sie jüngeren Kindern die Seite Für Kinder vor. Dort steht in einfachen Sätzen, was bei mir passiert.","Jugendliche möchten oft selbst entscheiden. Zeigen Sie ihnen die Seite Für dich, und lassen Sie sie mitentscheiden, ob sie zum Erstgespräch mitkommen."]
EL.append(('vorbereiten','<section id="vorbereiten" class="bh-um-sec" aria-labelledby="h-vorb"><h2 id="h-vorb" class="bh-h2">So bereiten Sie Ihr Kind vor</h2><ul class="bh-tips">'+''.join(f'<li class="bh-tips-li">{t}</li>' for t in tips)+'</ul><p class="bh-after"><a href="/fuer-kinder" class="bh-tlink">Zur Seite Für Kinder</a></p></section>'))
EL.append(('kosten','<section id="kosten" class="bh-kost" aria-labelledby="h-elk"><h2 id="h-elk" class="bh-h2">Was eine Sitzung kostet</h2>'+__import__('start').costs(True)+'<p class="bh-after"><a href="/ablauf-und-kosten" class="bh-tlink">Ablauf und Kosten im Einzelnen</a></p></section>'))
EL.append(('telefon','<section class="bh-tel" aria-labelledby="h-elt"><div><h2 id="h-elt" class="bh-h2">Der erste Schritt ist ein Anruf</h2><p class="bh-tel-big"><span class="bh-mark">Montag bis Donnerstag, 08:45 bis 10:00 Uhr</span></p><p class="bh-tel-note">In dieser Zeit gehe ich selbst ans Telefon. Sonst hören Sie den Anrufbeantworter.</p></div><div class="bh-tel-act"><a href="tel:+4930" class="bh-btn-l">030 [Nummer] anrufen</a><a href="/haeufige-fragen" class="bh-tlink">Häufige Fragen</a></div></section>'))

KQ=[("Wer ist Antonia?","Ich heiße Antonia Behr. Ich helfe Kindern, wenn etwas schwer ist. Zum Beispiel, wenn man oft Angst hat, wenn man lange traurig ist oder wenn es zu Hause viel Streit gibt."),
("Was machen wir zusammen?","Wir reden miteinander. Wir spielen, malen oder bauen auch etwas. Du musst dabei nichts können und nichts richtig machen."),
("Wie lange dauert das?","Eine Stunde bei mir dauert 50 Minuten. Meistens kommst du einmal in der Woche. Am Anfang kommen deine Eltern mit."),
("Erzähle ich alles weiter?","Was du mir erzählst, bleibt bei mir. Mit deinen Eltern rede ich auch. Vorher sage ich dir, worüber. Nur wenn ich glaube, dass du in Gefahr bist, muss ich jemandem Bescheid sagen. Das sage ich dir dann vorher."),
("Und wenn ich keine Lust habe?","Das darfst du mir sagen. Manche Kinder möchten am Anfang lieber nicht reden. Dann spielen wir erst einmal. Du bestimmst mit, was wir machen."),
("Darf ich etwas fragen?","Du darfst mich alles fragen. Wenn du etwas wissen möchtest, frag einfach beim ersten Treffen.")]
kid='<section class="bh-kid" aria-labelledby="h-kid"><h1 id="h-kid" class="bh-kid-h1">Für Kinder</h1><p class="bh-kid-lead">Diese Seite ist zum Vorlesen. Vielleicht liest sie dir jemand vor. Du kannst sie auch selbst lesen.</p><div class="bh-kblock">'+''.join(f'<h2 class="bh-kblock-h">{q}</h2><p class="bh-kblock-p">{a}</p>' for q,a in KQ)+'<div class="bh-kid-room">Platzhalter: Foto vom Spielregal oder vom Praxisraum, ohne Personen</div></div><p class="bh-kid-parents">Für Erwachsene: Mehr zu Ablauf, Elterngesprächen und Kosten steht auf der Seite <a href="/fuer-eltern" class="bh-tlink-ink">Für Eltern</a>.</p></section>'
KI=[('kinder',kid)]
