from sys_ import *
import start
c=start.c
# ---------- shared page head
c.add('.bh-phead',SEC,{**box(["clamp(56px, 7vw, 96px)",PADX,"0px",PADX])})
c.add('.bh-ph1',{"margin-top":"0px","margin-bottom":"16px","font-family":HF,"font-weight":"700","font-size":"clamp(2.6rem, 4vw + 1rem, 5rem)","line-height":"1.02","letter-spacing":"-0.015em","color":INK,"text-wrap":"balance"})
c.add('.bh-plead',{"margin-top":"0px","margin-bottom":"0px","max-width":"60ch","font-size":"1.25rem"})
c.add('.bh-h3',H3)
# ================= FÜR DICH
c.add('.bh-fd',SEC,{"background-color":VIOLET,"color":PAPER,**box(["clamp(56px, 7vw, 96px)",PADX,"clamp(72px, 9vw, 128px)",PADX])})
c.add('.bh-fd-h1',{"margin-top":"0px","margin-bottom":"16px","font-family":HF,"font-weight":"700","font-size":"clamp(2.8rem, 4vw + 1rem, 5rem)","line-height":"1.02","color":PAPER})
c.add('.bh-fd-lead',{"margin-top":"0px","margin-bottom":"0px","max-width":"52ch","font-size":"1.25rem","color":"#E9E2F4"})
c.add('.bh-block',{"margin-top":"56px","max-width":"860px","background-color":"#FFFFFF","color":INK,**rad("4px"),"background-image":"repeating-linear-gradient(transparent 0px, transparent 31px, #D9E1EC 31px, #D9E1EC 32px)","background-position":"0 36px","border-top":f"10px dotted {VIOLET}",**box(["40px","clamp(20px, 5vw, 64px)","48px","clamp(20px, 5vw, 64px)"]),"line-height":"32px"})
c.add('.bh-block-h',{"margin-top":"32px","margin-bottom":"0px","font-family":HF,"font-weight":"700","font-size":"1.5rem","line-height":"32px","color":INK})
c.add('.bh-block-p',{"margin-top":"0px","margin-bottom":"0px","max-width":"66ch"})
c.add('.bh-block-cta',{"display":"flex","flex-wrap":"wrap","align-items":"center","column-gap":"24px","row-gap":"8px","margin-top":"32px"})
c.add('.bh-btn-v',BTN,{"background-color":VIOLET}); c.add('.bh-btn-v:hover',BTN_H); c.add('.bh-btn-v:focus',FOCUS)
c.add('.bh-tlink-v',TLINK,{"text-decoration-color":VIOLET}); c.add('.bh-tlink-v:hover',{"color":VIOLET}); c.add('.bh-tlink-v:focus',FOCUS)
qa=[("Erfahren meine Eltern alles?","Nein. Was du mir erzählst, bleibt bei mir. Ich habe Schweigepflicht, auch gegenüber deinen Eltern. In den Elterngesprächen geht es darum, wie sie dich unterstützen können. Was ich dort sage, besprechen wir vorher. Eine Ausnahme gibt es: wenn ich mir ernste Sorgen um deine Sicherheit mache. Dann sage ich es dir, bevor ich mit jemandem spreche."),
("Muss ich reden, wenn ich nicht will?","Nein. Du bestimmst, worüber wir sprechen und wie schnell. Manche Stunden sind eher still, das ist in Ordnung. Wenn dir etwas zu viel wird, sag es. Oder wir machen vorher ein Zeichen aus."),
("Bin ich zu alt oder nicht krank genug?",'Ich arbeite mit jungen Menschen <span class="bh-mark">bis 21 Jahre</span>. Du musst nicht erst richtig krank sein. Wenn dich etwas seit längerer Zeit belastet, ist das Grund genug für ein Gespräch. Ob Therapie für dich passt, schauen wir im Erstgespräch zusammen an.'),
("Kann ich mich selbst melden?",'Ja. Ruf an, <span class="bh-mark">Montag bis Donnerstag, 08:45 bis 10:00 Uhr</span>. Ab 18 entscheidest du allein. Wenn du jünger bist, brauchen wir für die Therapie meistens auch deine Eltern. Wie das gut gehen kann, klären wir zusammen.'),
("Wie läuft eine Stunde ab?","50 Minuten, einmal pro Woche, in meinem Praxisraum in Mitte. Wir reden, manchmal schreiben oder skizzieren wir etwas. Es gibt nichts zu bestehen.")]
fd='<section class="bh-fd" aria-labelledby="h-fd"><h1 id="h-fd" class="bh-fd-h1">Für dich</h1><p class="bh-fd-lead">Wenn du 14 bist oder älter. Deine Eltern haben ihren eigenen Bereich. Das hier ist deiner.</p><div class="bh-block">'
fd+=''.join(f'<h2 class="bh-block-h">{q}</h2><p class="bh-block-p">{a}</p>' for q,a in qa)
fd+='<div class="bh-block-cta"><a href="tel:+4930" class="bh-btn-v">030 [Nummer] anrufen</a><a href="/kontakt#rueckruf" class="bh-tlink-v">Lieber einen Rückruf anfragen</a></div><h2 class="bh-block-h">Wenn es dir gerade sehr schlecht geht</h2><p class="bh-block-p">Nummer gegen Kummer, anonym und kostenlos: <span class="bh-markb">116 111</span>. Bei Lebensgefahr: <span class="bh-markb">112</span>.</p></div></section>'
FD=[('fuerdich',fd)]
# ================= ABLAUF UND KOSTEN
AK=[]
AK.append(('head','<section class="bh-phead"><h1 class="bh-ph1">Ablauf und Kosten</h1><p class="bh-plead">Vom ersten Anruf bis zur wöchentlichen Sitzung, und was Sie dafür bezahlen.</p></section>'))
steps=[("Anrufen",'Sie rufen zu den Telefonzeiten an, <span class="bh-mark">Montag bis Donnerstag, 08:45 bis 10:00 Uhr</span>. Wir sprechen kurz über das Alter Ihres Kindes, Ihre Versicherung und einen Termin.'),("Erstgespräch","Sie kommen gemeinsam mit Ihrem Kind. Bei Jugendlichen spreche ich auch einen Teil der Zeit allein mit ihnen."),("Kennenlernen","In einigen Sitzungen klären wir, ob die Therapie passt und woran wir arbeiten. Danach bekommen Sie eine Rückmeldung von mir."),("Therapie",'Ihr Kind kommt einmal pro Woche für 50 Minuten. <span class="bh-mark">Alle vier Sitzungen</span> gibt es ein Gespräch mit Ihnen als Eltern.')]
c.add('.bh-step',{"margin-bottom":"24px"})
AK.append(('ablauf','<section class="bh-abl" aria-labelledby="h-ab"><div><h2 id="h-ab" class="bh-h2">Der Ablauf</h2>'+''.join(f'<div class="bh-step"><h3 class="bh-h3">{h}</h3><p class="bh-p">{t}</p></div>' for h,t in steps)+'</div>'+start.plan(8,False)+'</section>'))
c.add('.bh-kgrid',{"display":"grid","grid-template-columns":"repeat(auto-fit, minmax(min(100%, 320px), 1fr))","column-gap":"48px","row-gap":"24px","max-width":"1040px","margin-top":"40px"})
AK.append(('kosten','<section class="bh-kost" aria-labelledby="h-ko"><h2 id="h-ko" class="bh-h2">Die Kosten</h2>'+start.costs(False)+'<div class="bh-kgrid"><div><h3 class="bh-h3">Private Krankenversicherung und Beihilfe</h3><p class="bh-p">Welcher Anteil erstattet wird, hängt von Ihrem Tarif ab. Fragen Sie vor Beginn bei Ihrer Versicherung nach, ob eine Genehmigung nötig ist und wie viele Sitzungen Ihr Tarif vorsieht.</p></div><div><h3 class="bh-h3">Selbstzahler nach GOP</h3><p class="bh-p">Sie bezahlen die Sitzungen selbst, ohne dass eine Versicherung davon erfährt. Die Rechnung kommt monatlich.</p></div></div></section>'))
c.add('.bh-ke',SEC,GRIDBG,{"margin-top":"clamp(72px, 9vw, 128px)",**box(["clamp(56px, 8vw, 112px)",PADX,"clamp(56px, 8vw, 112px)",PADX])})
c.add('.bh-steps',{"max-width":"880px","border-top":f"1.5px solid {INK}","margin-top":"32px"})
c.add('.bh-steps-row',{"display":"grid","grid-template-columns":"160px minmax(0px, 1fr)","column-gap":"24px",**box(["16px","0px","16px","0px"]),"border-bottom":f"1px solid {LINE}"})
c.add('.bh-steps-row',{"grid-template-columns":"1fr","row-gap":"4px"},media=SM)
c.add('.bh-steps-n',{"font-family":HF,"font-weight":"600"})
ks=['Über die Terminservicestelle <span class="bh-markb">116 117</span> einen Termin für eine psychotherapeutische Sprechstunde vereinbaren.','Dort die Bescheinigung über den Behandlungsbedarf mitnehmen.','Bei Praxen mit Kassenzulassung nach einem Platz fragen und die Absagen mit Datum notieren.','Den Antrag auf Kostenerstattung bei Ihrer Krankenkasse stellen, mit Bescheinigung und Absageliste. Ich gebe Ihnen dafür eine Bestätigung mit.','Erst nach der Genehmigung beginnen. Sie reichen meine Rechnungen dann bei der Kasse ein.']
AK.append(('erstattung','<section id="kostenerstattung" class="bh-ke" aria-labelledby="h-ke"><h2 id="h-ke" class="bh-h2">Kostenerstattung für gesetzlich Versicherte</h2><p class="bh-p">Wenn Ihre Krankenkasse in zumutbarer Zeit keinen Therapieplatz vermitteln kann, können Sie die Übernahme einer privaten Behandlung beantragen. Die Entscheidung trifft die Krankenkasse.</p><ol class="bh-steps">'+''.join(f'<li class="bh-steps-row"><span class="bh-steps-n">Schritt {i+1}</span><span>{t}</span></li>' for i,t in enumerate(ks))+'</ol></section>'))
c.add('.bh-steps',{"list-style-type":"none",**box(["0px"]*4),"margin-bottom":"0px"})
# ================= KONTAKT
KO=[]
c.add('.bh-ko-top',SEC,{"display":"grid","grid-template-columns":"repeat(auto-fit, minmax(min(100%, 380px), 1fr))","column-gap":"72px","row-gap":"32px","align-items":"end",**box(["clamp(56px, 7vw, 96px)",PADX,"0px",PADX])})
c.add('.bh-ko-sub',{"margin-top":"32px","margin-bottom":"8px","font-family":HF,"font-weight":"600","font-size":"1.125rem"})
c.add('.bh-ko-big',{"margin-top":"0px","margin-bottom":"24px","font-family":HF,"font-weight":"700","font-size":"clamp(1.9rem, 3vw + 1rem, 3.2rem)","line-height":"1.15","font-variant-numeric":"tabular-nums"})
c.add('.bh-ko-lbl',LABEL,{"max-width":"380px","transform":"rotate(-1deg)"})
KO.append(('top','<section class="bh-ko-top"><div><h1 class="bh-ph1">Kontakt und Anfahrt</h1><p class="bh-ko-sub">Telefonzeiten</p><p class="bh-ko-big"><span class="bh-mark">Montag bis Donnerstag, 08:45 bis 10:00 Uhr</span></p><a href="tel:+4930" class="bh-btn-l">030 [Nummer] anrufen</a></div><div class="bh-ko-lbl"><p class="bh-lbl-date">Stand 29.09.2026</p><p class="bh-lbl-state"><span class="bh-mark">Erstgespräche möglich</span></p></div></section>'))
c.add('.bh-form-sec',SEC)
c.add('.bh-form',{"display":"grid","grid-template-columns":"repeat(2, minmax(0px, 1fr))","column-gap":"24px","row-gap":"20px","max-width":"760px","margin-top":"28px"})
c.add('.bh-form',{"grid-template-columns":"1fr"},media=SM)
c.add('.bh-field',{"display":"flex","flex-direction":"column","row-gap":"6px"})
c.add('.bh-field-w',{"display":"flex","flex-direction":"column","row-gap":"8px","grid-column-start":"1","grid-column-end":"-1"})
c.add('.bh-flabel',{"font-family":HF,"font-weight":"600","font-size":"0.9375rem","margin-bottom":"0px"})
c.add('.bh-input',{"min-height":"52px","margin-bottom":"0px",**box(["10px","14px","10px","14px"]),"background-color":"#FFFFFF",**brd("1.5px solid #9AA3B5"),**rad("4px"),"font-size":"1.0625rem","color":INK})
c.add('.bh-input:focus',{"border-top-color":BLUE,"border-right-color":BLUE,"border-bottom-color":BLUE,"border-left-color":BLUE,"outline-color":BLUE,"outline-width":"2px","outline-style":"solid","outline-offset":"0px"})
c.add('.bh-chips',{"display":"flex","flex-wrap":"wrap","column-gap":"8px","row-gap":"8px"})
c.add('.bh-chipr',{"display":"flex","align-items":"center","column-gap":"8px","min-height":"44px","margin-bottom":"0px",**box(["0px","14px","0px","12px"]),"background-color":"#FFFFFF",**brd("1.5px solid #9AA3B5"),**rad("4px"),"font-size":"0.9375rem","cursor":"pointer"})
c.add('.bh-chipr:hover',{"border-top-color":INK,"border-right-color":INK,"border-bottom-color":INK,"border-left-color":INK})
c.add('.bh-consent',{"display":"flex","align-items":"flex-start","column-gap":"10px","grid-column-start":"1","grid-column-end":"-1","font-size":"0.9375rem","margin-bottom":"0px"})
c.add('.bh-submit',BTN,{"justify-self":"start","border-top-style":"none","border-right-style":"none","border-bottom-style":"none","border-left-style":"none","cursor":"pointer"}); c.add('.bh-submit:hover',BTN_H); c.add('.bh-submit:focus',FOCUS)
c.add('.bh-note',{"margin-top":"0px","margin-bottom":"0px","max-width":"60ch","color":MUTED,"font-size":"1rem"})
form='''<form class="bh-form" name="Rueckruf" action="https://api.web3forms.com/submit" method="POST"><input type="hidden" name="access_key" value="0a3f3a6a-5c98-4271-a2c7-a27072b210ae"><input type="hidden" name="subject" value="Rückrufwunsch über praxis-behr Website"><input type="hidden" name="from_name" value="Website Praxis Behr"><div class="bh-field"><label class="bh-flabel" for="bh-name">Ihr Name</label><input class="bh-input" id="bh-name" name="Name" type="text" autocomplete="name" required></div><div class="bh-field"><label class="bh-flabel" for="bh-tel">Telefon</label><input class="bh-input" id="bh-tel" name="Telefon" type="tel" autocomplete="tel" required></div><div class="bh-field"><label class="bh-flabel" for="bh-mail">E-Mail (freiwillig)</label><input class="bh-input" id="bh-mail" name="email" type="email" autocomplete="email"></div><div class="bh-field"><label class="bh-flabel" for="bh-age">Alter des Kindes</label><input class="bh-input" id="bh-age" name="Alter des Kindes" type="number" min="0" max="21" inputmode="numeric" required></div><div class="bh-field-w"><span class="bh-flabel">Versicherung</span><div class="bh-chips"><label class="bh-chipr"><input type="radio" name="Versicherung" value="Privat versichert" required>Privat versichert</label><label class="bh-chipr"><input type="radio" name="Versicherung" value="Beihilfe">Beihilfe</label><label class="bh-chipr"><input type="radio" name="Versicherung" value="Selbstzahler">Selbstzahler</label><label class="bh-chipr"><input type="radio" name="Versicherung" value="Gesetzlich, mit Kostenerstattung">Gesetzlich, mit Kostenerstattung</label></div></div><div class="bh-field-w"><span class="bh-flabel">Wann passt ein Rückruf?</span><div class="bh-chips"><label class="bh-chipr"><input type="radio" name="Rueckrufzeit" value="Vormittags, 9 bis 12 Uhr" required>Vormittags, 9 bis 12 Uhr</label><label class="bh-chipr"><input type="radio" name="Rueckrufzeit" value="Mittags, 12 bis 14 Uhr">Mittags, 12 bis 14 Uhr</label><label class="bh-chipr"><input type="radio" name="Rueckrufzeit" value="Nachmittags, 14 bis 17 Uhr">Nachmittags, 14 bis 17 Uhr</label></div></div><label class="bh-consent"><input type="checkbox" name="Einwilligung" value="ja" required>Ich bin einverstanden, dass meine Angaben für den Rückruf gespeichert und über den Formulardienst Web3Forms an die Praxis übermittelt werden. Mehr dazu in der Datenschutzerklärung.</label><button type="submit" class="bh-submit">Rückruf anfragen</button></form>'''
KO.append(('form',f'<section id="rueckruf" class="bh-form-sec" aria-labelledby="h-rr"><h2 id="h-rr" class="bh-h2">Rückruf anfragen</h2><p class="bh-note">Falls Sie die Telefonzeiten nicht schaffen. Bitte schreiben Sie hier noch nichts zu Beschwerden, darüber sprechen wir persönlich.</p>{form}</section>'))
c.add('.bh-anf',SEC,{"display":"grid","grid-template-columns":"repeat(auto-fit, minmax(min(100%, 380px), 1fr))","column-gap":"72px","row-gap":"32px",**box(["clamp(72px, 9vw, 128px)",PADX,"clamp(72px, 9vw, 128px)",PADX])})
c.add('.bh-map',PH,{"min-height":"360px","border-top-style":"dashed","border-right-style":"dashed","border-bottom-style":"dashed","border-left-style":"dashed"})
KO.append(('anfahrt','<section class="bh-anf" aria-labelledby="h-anf"><div><h2 id="h-anf" class="bh-h2">Anfahrt</h2><p class="bh-p">Praxis Antonia Behr<br>[Straße und Hausnummer]<br>[PLZ] Berlin-Mitte</p><p class="bh-p">[U-Bahn, S-Bahn oder Tram mit Haltestelle und Fußweg]</p><p class="bh-p">[Zugang: Etage, Aufzug, Stufen]</p></div><div class="bh-map">Platzhalter: Kartenausschnitt oder Foto vom Hauseingang. Eine Karte bitte nur als statisches Bild oder erst nach Klick laden.</div></section>'))
