from sys_ import *
import faqp
c=faqp.c
c.add('.bh-um-hero',SEC,{"display":"grid","grid-template-columns":"repeat(auto-fit, minmax(min(100%, 340px), 1fr))","column-gap":"72px","row-gap":"40px","align-items":"end",**box(["clamp(56px, 7vw, 96px)",PADX,"0px",PADX])})
c.add('.bh-um-intro',{"max-width":"58ch"})
c.add('.bh-um-role',{"margin-top":"0px","margin-bottom":"28px","font-size":"1.25rem"})
c.add('.bh-um-sec',SEC)
c.add('.bh-um-lead',{"margin-top":"0px","margin-bottom":"32px","max-width":"60ch"})
c.add('.bh-hold',{"display":"grid","grid-template-columns":"repeat(auto-fit, minmax(min(100%, 280px), 1fr))","column-gap":"48px","row-gap":"8px","max-width":"1040px"})
c.add('.bh-hold-item',{"padding-top":"16px","border-top":f"1.5px solid {INK}"})
c.add('.bh-tl',{"list-style-type":"none",**box(["0px"]*4),"margin-top":"0px","margin-bottom":"0px","max-width":"880px","border-top":f"1.5px solid {INK}"})
c.add('.bh-tl-row',{"display":"grid","grid-template-columns":"140px minmax(0px, 1fr)","column-gap":"24px",**box(["16px","0px","16px","0px"]),"border-bottom":f"1px solid {LINE}"})
c.add('.bh-tl-row',{"grid-template-columns":"1fr","row-gap":"2px"},media=SM)
c.add('.bh-tl-y',{"font-family":HF,"font-weight":"600","font-variant-numeric":"tabular-nums"})
c.add('.bh-um-grid',SEC,GRIDBG,{"margin-top":"clamp(72px, 9vw, 128px)",**box(["clamp(56px, 8vw, 112px)",PADX,"clamp(56px, 8vw, 112px)",PADX])})
c.add('.bh-um-cols',{"display":"grid","grid-template-columns":"repeat(auto-fit, minmax(min(100%, 320px), 1fr))","column-gap":"64px","row-gap":"32px","max-width":"1040px"})

S=[]
S.append(('hero','<section class="bh-um-hero" aria-labelledby="h-um"><div class="bh-portrait" role="img" aria-label="Platzhalter Porträt">Platzhalter: Porträt, Frau Behr sitzend auf Augenhöhe im Praxisraum, Tageslicht</div><div class="bh-um-intro"><h1 id="h-um" class="bh-ph1">Über mich</h1><p class="bh-um-role">Antonia Behr, Kinder- und Jugendlichenpsychotherapeutin in Berlin-Mitte</p><p class="bh-p">Ich arbeite mit Kindern, Jugendlichen und jungen Erwachsenen <span class="bh-mark">bis 21 Jahre</span> und beziehe die Familie ein, so viel wie hilfreich ist. Meine Approbation habe ich im Verfahren Verhaltenstherapie.</p><p class="bh-p">[Zwei bis drei Sätze in eigenen Worten: warum diese Arbeit, was Ihnen wichtig ist.]</p><div class="bh-hand">Platzhalter: Scan, ein Satz in Frau Behrs Handschrift</div></div></section>'))
hold=[("Ernst nehmen, was Kinder sagen","Kinder und Jugendliche sind Expertinnen und Experten für ihr eigenes Leben. Ich höre zu, bevor ich etwas vorschlage, und erkläre, was ich tue und warum."),
("Eltern als Partner","Eltern kennen ihr Kind am besten. In den regelmäßigen Elterngesprächen überlegen wir gemeinsam, was zu Hause hilft, ohne Schuldzuweisungen."),
("Offen über Grenzen","Ich sage ehrlich, was eine Therapie leisten kann und was nicht. Wenn eine andere Stelle besser passt, sage ich Ihnen das.")]
S.append(('haltung','<section class="bh-um-sec" aria-labelledby="h-hal"><h2 id="h-hal" class="bh-h2">Wie ich arbeite</h2><p class="bh-um-lead">Drei Grundsätze, die für jede Therapie in meiner Praxis gelten.</p><div class="bh-hold">'+''.join(f'<div class="bh-hold-item"><h3 class="bh-h3">{h}</h3><p class="bh-p">{t}</p></div>' for h,t in hold)+'</div></section>'))
tl=[("[Jahr]","Studium der [Psychologie oder (Sozial)pädagogik] an der [Hochschule]"),("[Jahr]","Ausbildung zur Kinder- und Jugendlichenpsychotherapeutin, Schwerpunkt Verhaltenstherapie, am [Ausbildungsinstitut]"),("[Jahr]","Approbation als [Berufsbezeichnung laut Approbation]"),("[Jahr bis Jahr]","[Klinische Stationen, z. B. Kinder- und Jugendpsychiatrie, Beratungsstelle, Ambulanz]"),("seit [Jahr]","Eigene Privatpraxis in Berlin-Mitte"),("[laufend]","[Fortbildungen und Zusatzqualifikationen, z. B. Traumatherapie, Elterntraining]")]
S.append(('werdegang','<section class="bh-um-sec" aria-labelledby="h-wg"><h2 id="h-wg" class="bh-h2">Werdegang</h2><ol class="bh-tl">'+''.join(f'<li class="bh-tl-row"><span class="bh-tl-y">{y}</span><span>{t}</span></li>' for y,t in tl)+'</ol></section>'))
S.append(('verfahren','<section class="bh-um-grid" aria-labelledby="h-vf"><h2 id="h-vf" class="bh-h2">Verhaltenstherapie, verständlich erklärt</h2><div class="bh-um-cols"><div><h3 class="bh-h3">Was das heißt</h3><p class="bh-p">In der Verhaltenstherapie schauen wir auf das, was im Alltag schwierig ist: Gedanken, Gefühle und Verhalten, die sich festgefahren haben. Gemeinsam probieren wir in kleinen Schritten aus, was hilft, und üben es auch zwischen den Stunden.</p><p class="bh-p">Mit jüngeren Kindern geschieht das viel über Spiel, Malen und Geschichten, mit Jugendlichen eher im Gespräch. Die Verhaltenstherapie ist ein wissenschaftlich anerkanntes Verfahren.</p></div><div><h3 class="bh-h3">Psychotherapeutin oder Kinderpsychologin?</h3><p class="bh-p">Viele Eltern suchen zuerst nach einer Kinderpsychologin. Der Unterschied: Als approbierte Psychotherapeutin darf ich psychische Erkrankungen feststellen und behandeln. Der Titel ist gesetzlich geschützt und setzt eine mehrjährige Ausbildung und eine staatliche Prüfung voraus.</p><p class="bh-p">Kinder- und Jugendpsychiaterinnen sind Ärztinnen und können zusätzlich Medikamente verordnen. Wenn das sinnvoll ist, arbeiten wir zusammen.</p></div></div></section>'))
S.append(('rahmen','<section class="bh-um-sec" aria-labelledby="h-rf"><h2 id="h-rf" class="bh-h2">Rahmen und Verpflichtungen</h2><div class="bh-um-cols"><div><h3 class="bh-h3">Schweigepflicht</h3><p class="bh-p">Alles, was in der Praxis besprochen wird, unterliegt der gesetzlichen Schweigepflicht, auch gegenüber Schule, Arbeitgeber und Krankenkasse, soweit Sie nicht ausdrücklich zustimmen.</p></div><div><h3 class="bh-h3">Kammer und Qualität</h3><p class="bh-p">Ich bin Mitglied der Psychotherapeutenkammer Berlin und an deren Berufsordnung gebunden. Ich bilde mich regelmäßig fort und bespreche meine Arbeit in [Intervision oder Supervision].</p></div></div></section>'))
S.append(('telefon','<section class="bh-tel" aria-labelledby="h-kontakt2"><div><h2 id="h-kontakt2" class="bh-h2">Lernen wir uns kennen</h2><p class="bh-tel-big"><span class="bh-mark">Montag bis Donnerstag, 08:45 bis 10:00 Uhr</span></p><p class="bh-tel-note">In dieser Zeit gehe ich selbst ans Telefon. Sonst hören Sie den Anrufbeantworter.</p></div><div class="bh-tel-act"><a href="tel:+4930" class="bh-btn-l">030 [Nummer] anrufen</a><a href="/haeufige-fragen" class="bh-tlink">Häufige Fragen</a></div></section>'))
